---
title: "STATS 782 Assignment 1; University of Auckland"
date: 'Due Date: 10:00 NZ Time, Monday 20 March 2023'
output:
  html_document: default
  pdf_document: default
---

### "Junyi Yang", "223831196"

I have read the declaration on the cover sheet and confirm my agreement with it.


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE) ## makes sure the code is shown
```


## Question 1

### a)

```{r}
seq(0,6,by=1.5)
```

### b)

```{r}
cumsum(seq(2,20,by=2))
```

### c)

```{r}
abs(3:-3)
```

### d)

```{r}
rep(seq(40,0,by=-10),times = 4) + rep(0:4,each=4)
```

### e)

```{r}
paste(LETTERS[7:1],7:1,'-',letters[1:7],1:7,sep = '')
```



## Question 2

```{r}
## define f here
f = function (x) {
  # max index is the length for the longest one
  index_s = 0
  index_e = 0
  max = 0
  
  # we also need to return the empty and 
  # length 1's situation 
  if (length(x)<=1) {
    return(numeric(0))
  }
  
  
  # this is the normal part
  for (i in (1:(length(x)-1))){
    
    # if we have find the part
    # for we assume that the length of the partition will be >= 2
    if(x[i]>x[i+1]){
      start = i
      end = i+1
      len = 2
      
      # if we have reached the end of the x, we just out
      if (i==length(x)-1){
        if(max<len){
          max = len
          index_s = start
          index_e = end
        }
        break
      }
      
      # if we have not, we should go down
      for (j in (i+1):(length(x)-1)){
        if(x[j]>x[j+1]){
          len = len+1
          end = j+1
        }
        # there is no decreasing 
        else{
          break
        }
      }
      
      # if we have found new one, we should update the index and the max value
      if (max<len){
        max = len
        index_s = start
        index_e = end
      }
      else{
        start = 0
        end = 0
      }
    
    }
  }
  
  if(index_s == index_e){
    return (numeric(0))
  }
  
  x[index_s:index_e]
}
```

```{r}
## uncomment the tests when you are done
x <- c(-1, 2, 7, 5.5, 5, 4, 4, 3, 2, -4, -4.1, -5, 8)

f(x)

set.seed(782)
f(0)
f(3:1)
f(1:3)
f(c(Inf, 0, -Inf, pi, 3))
f(round(runif(100) * 100, 1))
```


## Question 3

### a)

```{r}
# at first we need to do the preparation for the data 
library(MASS)

state <- rownames(road) # name of the US state
deaths <- road$deaths # number of deaths
drivers <- road$drivers # number of drivers (in 10,000s)
temp <- road$temp # average daily max temperature in January
```

#### We need a new chunk to create the main part:

```{r}
max(deaths)
```


### b)

```{r}
mean(deaths)
```

### c)

```{r}
# to get this result we need to get
# the fatality rate = number of deaths / number of drivers

fatality_rate = deaths / drivers

# then get the index for the max
index = which.max(fatality_rate)

# then we get the name 
state[index]
```

### d)

```{r}
# at first we need to get he average number of deaths
avg = mean(deaths)

# then we get the close rank for the deaths R
close = state[order(abs(deaths-avg))][1:3]
close
```

### e)

```{r}
# if we want the at least 100,000 drivers
# we need to change get the drivers' items

over_drivers_index = which((drivers / 10)>=1)

# then we calculate the highest fatality rates
fatality_rate_per = deaths[over_drivers_index] / (drivers*100000)[over_drivers_index]

# then we get 3 the highest rates
state[over_drivers_index][order(fatality_rate_per)][1:3]


```


## Question 4

### a)

```{r}

```

### b)

```{r}
## define f here

# f(1000)
```

### c)

```{r}
## define approx here

```
(explain here or in comments)

```{r}
# approx(0.00001)
```

### d)

```{r}
## define sr here

# sr(n = 4)
# compare and explain
```

### e)

```{r}

```

### f)

```{r}

```
